<?xml version="1.0" encoding="utf-8"?><Database Name="EVENT_SOCIAL_NETWORK" Class="ESNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EventSocialNetwork.mssql.somee.com;Initial Catalog=EventSocialNetwork;Persist Security Info=False;User ID=hoangnam;Packet Size=4096;Workstation ID=EventSocialNetwork.mssql.somee.com" SettingsObjectName="ESNLibrary.Properties.Settings" SettingsPropertyName="EVENT_SOCIAL_NETWORKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Account_AccountInfo" Member="AccountInfo" ThisKey="AccID" OtherKey="AccID" Type="AccountInfo" Cardinality="One" />
      <Association Name="Account_Comment" Member="Comments" ThisKey="AccID" OtherKey="AccID" Type="Comment" />
      <Association Name="Account_EventInfo" Member="EventInfos" ThisKey="AccID" OtherKey="AccID" Type="EventInfo" />
      <Association Name="Account_EventTrustDetail" Member="EventTrustDetails" ThisKey="AccID" OtherKey="AccID" Type="EventTrustDetail" />
      <Association Name="Account_Relation" Member="Relations" ThisKey="AccID" OtherKey="FriendID" Type="Relation" />
      <Association Name="Account_Relation1" Member="Relations1" ThisKey="AccID" OtherKey="AccID" Type="Relation" />
      <Association Name="Account_Suggestion" Member="Suggestions" ThisKey="AccID" OtherKey="AccID" Type="Suggestion" />
      <Association Name="Account_UserLocation" Member="UserLocations" ThisKey="AccID" OtherKey="AccID" Type="UserLocation" />
      <Association Name="Account_Activity" Member="Activities" ThisKey="AccID" OtherKey="AccID" Type="Activity" />
      <Association Name="Account_Activity1" Member="Activities1" ThisKey="AccID" OtherKey="FriendID" Type="Activity" />
      <Association Name="Role_Account" Member="Role" ThisKey="RoleID" OtherKey="RoleID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebsiteInfo" Member="WebsiteInfos">
    <Type Name="WebsiteInfo">
      <Column Name="WebsiteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WebsiteURL" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.AccountInfo" Member="AccountInfos">
    <Type Name="AccountInfo">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Favorite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccessToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VerificationCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_AccountInfo" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="ShareType_AccountInfo" Member="ShareType" ThisKey="ShareID" OtherKey="ShareID" Type="ShareType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityType" Member="ActivityTypes">
    <Type Name="ActivityType">
      <Column Name="ActiTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActiTypeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ActivityType_Activity" Member="Activities" ThisKey="ActiTypeID" OtherKey="ActiTypeID" Type="Activity" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Comment_Activity" Member="Activities" ThisKey="CommentID" OtherKey="CommentID" Type="Activity" />
      <Association Name="Account_Comment" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="EventInfo_Comment" Member="EventInfo" ThisKey="EventID" OtherKey="EventID" Type="EventInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventInfo" Member="EventInfos">
    <Type Name="EventInfo">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EventInfo_Comment" Member="Comments" ThisKey="EventID" OtherKey="EventID" Type="Comment" />
      <Association Name="EventInfo_EventTrustDetail" Member="EventTrustDetails" ThisKey="EventID" OtherKey="EventID" Type="EventTrustDetail" />
      <Association Name="EventInfo_Activity" Member="Activities" ThisKey="EventID" OtherKey="EventID" Type="Activity" />
      <Association Name="Account_EventInfo" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="EventType_EventInfo" Member="EventType" ThisKey="EventTypeID" OtherKey="EventTypeID" Type="EventType" IsForeignKey="true" />
      <Association Name="ShareType_EventInfo" Member="ShareType" ThisKey="ShareID" OtherKey="ShareID" Type="ShareType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventTrustDetail" Member="EventTrustDetails">
    <Type Name="EventTrustDetail">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="EventInfo_EventTrustDetail" Member="EventInfo" ThisKey="EventID" OtherKey="EventID" Type="EventInfo" IsForeignKey="true" />
      <Association Name="Account_EventTrustDetail" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventType" Member="EventTypes">
    <Type Name="EventType">
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventTypeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EventType_EventInfo" Member="EventInfos" ThisKey="EventTypeID" OtherKey="EventTypeID" Type="EventInfo" />
    </Type>
  </Table>
  <Table Name="dbo.Relation" Member="Relations">
    <Type Name="Relation">
      <Column Name="RelationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FriendID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Relation" Member="Account" ThisKey="FriendID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="Account_Relation1" Member="Account1" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="RelationType_Relation" Member="RelationType" ThisKey="RelationTypeID" OtherKey="RelationTypeID" Type="RelationType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RelationType" Member="RelationTypes">
    <Type Name="RelationType">
      <Column Name="RelationTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RelationTypeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="RelationType_Relation" Member="Relations" ThisKey="RelationTypeID" OtherKey="RelationTypeID" Type="Relation" />
      <Association Name="ShareType_RelationType" Member="ShareType" ThisKey="ShareID" OtherKey="ShareID" Type="ShareType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Role_Account" Member="Accounts" ThisKey="RoleID" OtherKey="RoleID" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.ShareType" Member="ShareTypes">
    <Type Name="ShareType">
      <Column Name="ShareID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ShareType_AccountInfo" Member="AccountInfos" ThisKey="ShareID" OtherKey="ShareID" Type="AccountInfo" />
      <Association Name="ShareType_EventInfo" Member="EventInfos" ThisKey="ShareID" OtherKey="ShareID" Type="EventInfo" />
      <Association Name="ShareType_RelationType" Member="RelationTypes" ThisKey="ShareID" OtherKey="ShareID" Type="RelationType" />
    </Type>
  </Table>
  <Table Name="dbo.Suggestion" Member="Suggestions">
    <Type Name="Suggestion">
      <Column Name="SuggestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_Suggestion" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLocation" Member="UserLocations">
    <Type Name="UserLocation">
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longtitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_UserLocation" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Activity" Member="Activities">
    <Type Name="Activity">
      <Column Name="ActiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FriendID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActiTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ActivityType_Activity" Member="ActivityType" ThisKey="ActiTypeID" OtherKey="ActiTypeID" Type="ActivityType" IsForeignKey="true" />
      <Association Name="Comment_Activity" Member="Comment" ThisKey="CommentID" OtherKey="CommentID" Type="Comment" IsForeignKey="true" />
      <Association Name="Account_Activity" Member="Account" ThisKey="AccID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="Account_Activity1" Member="Account1" ThisKey="FriendID" OtherKey="AccID" Type="Account" IsForeignKey="true" />
      <Association Name="EventInfo_Activity" Member="EventInfo" ThisKey="EventID" OtherKey="EventID" Type="EventInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SearchFriend" Method="SearchFriend">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Keyword" Parameter="keyword" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="SearchFriendResult">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateNewEvent" Method="CreateNewEvent">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventType" Parameter="eventType" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Lat" Parameter="lat" Type="System.Double" DbType="Float" />
    <Parameter Name="Lng" Parameter="lng" Type="System.Double" DbType="Float" />
    <Parameter Name="Picture" Parameter="picture" Type="System.String" DbType="VarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetHistoryLocation" Method="GetHistoryLocation">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetHistoryLocationResult">
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longtitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInvitation" Method="GetInvitation">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetInvitationResult">
      <Column Name="ActiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNotification" Method="GetNotification">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetNotificationResult">
      <Column Name="ActiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActiTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadAllEvent" Method="LoadAllEvent">
    <ElementType Name="LoadAllEventResult">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AccID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TimeExist" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadComment" Method="LoadComment">
    <Parameter Name="EventID" Parameter="eventID" Type="System.Int32" DbType="Int" />
    <ElementType Name="LoadCommentResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadEventInfo" Method="LoadEventInfo">
    <Parameter Name="EvenID" Parameter="evenID" Type="System.Int32" DbType="Int" />
    <ElementType Name="LoadEventInfoResult">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Status1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadEventType" Method="LoadEventType">
    <ElementType Name="LoadEventTypeResult">
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadHotedEvent" Method="LoadHotedEvent">
    <ElementType Name="LoadHotedEventResult">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AccID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TimeExist" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LoadNewestEvent" Method="LoadNewestEvent">
    <ElementType Name="LoadNewestEventResult">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AccID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TimeExist" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Login" Method="Login">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="LoginResult">
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Favorite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccessToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VerificationCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Register" Method="Register">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Pass" Parameter="pass" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BirthDay" Parameter="birthDay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="VerificationCode" Parameter="verificationCode" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.loadEvent" Method="loadEvent">
    <Parameter Name="lat1" Type="System.Double" DbType="Float" />
    <Parameter Name="long1" Type="System.Double" DbType="Float" />
    <Parameter Name="r" Type="System.Double" DbType="Float" />
    <ElementType Name="loadEventResult">
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventLat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EventLng" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Like]" Member="Like" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dislike" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelImage" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="AccID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TimeExist" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetMyActivity" Method="GetMyActivity">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetMyActivityResult">
      <Column Name="ActiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FriendID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActiTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetFriendLocation" Method="GetFriendLocation">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetFriendLocationResult">
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longtitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetFriendList" Method="GetFriendList">
    <Parameter Name="AccID" Parameter="accID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetFriendListResult">
      <Column Name="AccID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShareID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Favorite" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccessToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VerificationCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DayCreate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>