//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESNLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=EventSocialNetwork.mssql.somee.com;packet size=4096;user id=hoangn" +
            "am;pwd=nhn29121992;data source=EventSocialNetwork.mssql.somee.com;persist securi" +
            "ty info=False;initial catalog=EventSocialNetwork")]
        public string EVENT_SOCIAL_NETWORKConnectionString {
            get {
                return ((string)(this["EVENT_SOCIAL_NETWORKConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=EVENT_SOCIAL_NETWORK;Persist Security Info=True;Use" +
            "r ID=sa;Password=123")]
        public string EVENT_SOCIAL_NETWORKConnectionString1 {
            get {
                return ((string)(this["EVENT_SOCIAL_NETWORKConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KHANHHUNG-PC;Initial Catalog=EVENT_SOCIAL_NETWORK;Persist Security In" +
            "fo=True;User ID=sa;Password=toiyeuvn")]
        public string EVENT_SOCIAL_NETWORKConnectionString2 {
            get {
                return ((string)(this["EVENT_SOCIAL_NETWORKConnectionString2"]));
            }
        }
    }
}
